GET http://frozen-basin-35628.herokuapp.com/ HTTP/1.1
content-type: application/json

{

}

###
POST http://frozen-basin-35628.herokuapp.com/daily HTTP/1.1
content-type: application/json

{

"name": "Buroi Alexandra",
"cosemnat": "Szalai Laszlo"

}

###
GET http://frozen-basin-35628.herokuapp.com/xlsx/2020/10 HTTP/1.1
content-type: application/json

{

}

###
GET http://localhost:3000/xlsx/2020/10 HTTP/1.1
content-type: application/json

{

}

###
POST http://localhost:3000/daily HTTP/1.1
content-type: application/json

{

"name": "Buroi Alexandra",
"cosemnat": "Szalai Laszlo"

}