GET http://frozen-basin-35628.herokuapp.com/ HTTP/1.1
content-type: application/json

{

}

###
POST http://frozen-basin-35628.herokuapp.com/daily HTTP/1.1
content-type: application/json

[{

"name": "Buroi Alexandra",
"cosemnat": "Szalai Laszlo"

},
{

"name": "Putnoki Lorand",
"cosemnat": "Szalai Laszlo"

}
]

###
GET http://frozen-basin-35628.herokuapp.com/xlsx/2020/11 HTTP/1.1
content-type: application/json

{

}

###
GET http://localhost:3001/xlsx/2020/11 HTTP/1.1
content-type: application/json

{

}

###
POST http://localhost:3001/daily HTTP/1.1
content-type: application/json

[
{
"name": "Szalai Laszlo",
"date": "2020-11-17T08:48:13.682Z",
"cosemnat": "Szalai Laszlo"
 },
{
"name": "Berki Melinda",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Buroi Alexandra",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Covaci Emilia",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Cordovan Loredana",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Kanalas Monika",
"cosemnat": "Szalai Laszlo"
},
 {
"name": "Putnoki Lorand",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Simon Angela",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Cotrau Iuliana",
"cosemnat": "Szalai Laszlo"
},
{
"name": "Magori Gabriela",
"cosemnat": "Gergely Livia"
},
 {
"name": "Lazar Bogdan",
"cosemnat": "Gergely Livia"
},
{
"name": "Iovan Florian",
"cosemnat": "Gergely Livia"
},
{
"name": "Abrudan Ioana",
"cosemnat": "Gergely Livia"
},
{
"name": "Covaci Csaba",
"cosemnat": "Gergely Livia"
 }
]

###
POST http://localhost:3001/signin HTTP/1.1
content-type: application/json

{
"name":"Livia",
"password":"compaq18"
}

###
GET http://localhost:3001/status HTTP/1.1
Content-Type:  application/json

{
    
}

###
POST http://localhost:3001/updateStatus HTTP/1.1
Content-Type:  application/json

{"status":{
    "name":"test",
    "planpers":"2020.01.12"
}
}

###

PUT http://localhost:3001/suspend HTTP/1.1
Content-Type:  application/json

{
    "suspend":{
        "name":"Abrudan Ioana"
    }
}

###
POST http://localhost:3001/list/add HTTP/1.1
Content-Type: application/json

{
    "list":[    
    {
        "name":"Abrudan Ioana"
         
    },
    {
        "name":"Barta Emese"
         
    },
    {
        "name":"Berki Melinda"
         
    },
    {
        "name":"Bojan Gheorghe"
         
    },
    {
        "name":"Borbely Marin"
         
    },
    {
        "name":"Bot Mariana"
         
    },
    {
        "name":"Buroi Alexandra"
         
    },
    {
        "name":"Buza Laura"
         
    },
    {
        "name":"Chirila Octavian"
         
    },
    {
        "name":"Cordovan Loredana"
         
    },
    {
        "name":"Cotrau Iuliana"
         
    },
    {
        "name":"Covaci Csaba"
         
    },
    {
        "name":"Covaci Emilia"
         
    },
    {
        "name":"Covaci Rodica"
         
    },
    {
        "name":"David Iuliana"
         
    },
    {
        "name":"Dragos Anamaria"
         
    },
    {
        "name":"Duta Gabriela"
         
    },
    {
        "name":"Eiben Hardy"
         
    },
    {
        "name":"Enache Dan"
         
    },
    {
        "name":"Farkas Eniko"
         
    },
    {
        "name":"Fekete Florica"
         
    },
    {
        "name":"Halmajan Bogdan"
         
    },
    {
        "name":"Haikai Ileana"
         
    },
    {
        "name":"Iacob Amalia"
         
    },
    {
        "name":"Indig Daniela"
         
    },
    {
        "name":"Iovan Florian"
         
    },
    {
        "name":"Jecan Norbert"
         
    },
    {
        "name":"Kanalas Monika"
         
    },
    {
        "name":"Kozak Ianos"
         
    },
    {
        "name":"Lakatos Maria"
         
    },
    {
        "name":"Lazar Bogdan"
         
    },
    {
        "name":"Magori Gabriela"
         
    },
    {
        "name":"Mascas Lucian"
         
    },
    {
        "name":"Murvai Alexandru"
         
    },
    {
        "name":"Mustea Tibor"
        
    },
    {
        "name":"Pacurar Raluca"
         
    },
    {
        "name":"Paraschiva Corina"
         
    },
    {
        "name":"Paunescu Luminita"
         
    },
    {
        "name":"Popa Etelca"
         
    },
    {
        "name":"Popa Mirela"
         
    },
    {
        "name":"Putnoki Lorand"
         
    },
    {
        "name":"Racz Monika"
         
    },
    {
        "name":"Rezmuves Dezso"
         
    },
    {
        "name":"Stoian Sorin"
         
    },
    {
        "name":"Simon Angela"
         
    },
    {
        "name":"Tenkei Tamas"
         
    },
    {
        "name":"Ungur Ioan"
         
    },
    {
        "name":"Varga Linda"
         
    },
    {
        "name":"Varga Augustin"
         
    },
    {
        "name":"Varga Jozsef"
         
    },
    {
        "name":"Zambo Gyorgy"
         
    }
    
]
}

###
POST https://oslogin.googleapis.com/v1/users/szalai.laszlo.istvan.psiho@gmail.com:importSshPublicKey

{
 "key": "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA5IrV/icLi7G4TQYaA0WevccQR12PoGMTfNkFBG79ASBJNWBSQo/URmTC/GEIDgx3eAwsJXreLFQE9xm7zHg1C9WaT2or/Qv2Vgz0gZ37N0c3Vo97hNuEU0i24ViELVXzaajJvqm3UkFLVmXvx1Lp8tHBkH0B0zt3q3JF00SO+n/Ed9KhPdECeUDq05ZHAfylQ2esFyZVQbVSponF1lb9pSLDv2p9GFNPXzR+fZVKl/IeG3qurP8FV0q4RzbovsARAiskmym++O088ktt6/efCIpf7xzt/tH8iwkkG3yyQjIB/etnBuCg7da3F9QYGYHYbVk4SPBgdJZ96JEn+5YYTQ== szalai_laszlo_istvan_psiho",
 
}